### PR TITLE
Use GitHub Actions for CI

### PR DESCRIPTION
**Pull request by Kernald**

### CODE REVIEW

**Comment by Kernald** [comment]
From what I understand, this won't run until a `.github` folder is present on `master`. I'll go ahead and merge this, and solve any potential issue as well as clean up the Cirrus integration in another PR.

**Comment by Kernald** [comment]
@patbro It looks like this repo (or `ProdriveTechnologies` overall, I'm not sure) disallows GitHub actions to run - I get the same issue as shown [here](https://github.com/orgs/community/discussions/25488). Is this something that you could address, or should we stick with Cirrus CI (in which case I'll have a look at how to run on macOS/Windows as well)?

**Comment by SimonBorger** [comment]
Hi @Kernald, could you see if it works now?

**Comment by Kernald** [comment]
> Hi @Kernald, could you see if it works now?

The build fails but the action is starting just fine (https://github.com/ProdriveTechnologies/bazel-latex/actions/runs/3180938745/jobs/5185102711), thanks! I'll have a closer look at that tomorrow :-)

**Pull request merged**
