### PR TITLE
Add bzlmod support

### PR DESCRIPTION
**Pull request by ljessendk**
This MR adds bzlmod support to bazel-latex.

A few changes were needed to do so:
- rules_python has been bumped to latest version (version 0.36.0).
- I had to disable the amd64-freebsd toolchain as this seems to be broken (missing the biber tool).
- I have introduced a 'hub' repository for all the texlive packages.

### CODE REVIEW

**Comment by Vertexwahn** [comment]
Awesome!

**Comment by solsjo** [comment]
Great @ljessendk 
Have not had time to review it/test it locally yet.

But if any of the others have time to review / merge I'll very much trust their verdict.

I did not see any commit updating the README, I think it would make sense to update that as well.

**Comment by solsjo** [comment]
@ljessendk 
I triggered the test pipeline and currently, 
- buildifier check fails
- mac os test faila to identify the ghost script target

**Comment by ljessendk** [comment]
> @ljessendk I triggered the test pipeline and currently,
> 
> * buildifier check fails
> * mac os test faila to identify the ghost script target

Both should be fixed now. 
The 4 test pipelines still fail, but they fail with the same error as on the master branch.

**Comment by Vertexwahn** [comment]
I tested it successfully with Ubuntu 22.04 (on x64) and macOS Sonma (on M1)! Works great! 

@solsjo I suggest to merge this!

**Review by Vertexwahn — APPROVED** [review]

**Comment by solsjo** [comment]
Agree! Great that you tested it @Vertexwahn! Havn't had time!

**Comment by solsjo** [comment]
I think dvisvgm fails because ghostscript is out-of-sync with ubuntu-latest. Which at the time of adding the dvisvgm targets probably was a prevous version of ubuntu.
Perhaps we ought to filter out the dvisvgm example targets for now?

**Comment by solsjo** [comment]
Thank you @ljessendk!

**Comment by solsjo** [comment]
@Vertexwahn the README should probably be update to reflect how to use the repo using bazel modules?

**Comment by Vertexwahn** [comment]
@solsjo See here -> https://github.com/ProdriveTechnologies/bazel-latex/pull/119

**Pull request merged**
